### ISSUE TITLE
Authenticating Users with Auth0 Universal Login

### ISSUE THREAD

**Issue by leojkwan** [superfit-athletics/android#28]
It looks like token refresh and storage is done for free using the CredentialsManager provided by the Android Auth0 library! https://auth0.com/docs/libraries/auth0-android/database-authentication

Notes:
- Take a look at universal login, we use the same mechanism on iOS, it just pulls up a secure web page with the auth screen hosted through Auth0.
- We’ll need to add an additional callback URL with ‘android’ specified in the URL. I *think* we can still use the same client app, and just add this url, but we’ll see. More info on this in the link above

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sufeiiz** [comment]
Okay a few questions:
1) sounds like they recommend universal login, so im leaning toward going down that route
2) Let's break this down further. I assume V1 will just handle being able to log in. And overtime we can add in signup, reset password, error states?
3) Can you provide me with a new `android` callback URL?

**Comment by leojkwan** [comment]
Luckily if we use universal login, the web page you load takes care of sign up sign in, reset as well as errors. Check out logging in via superfit iOS you’ll get a pop up with alll those features given free. We don’t build the UI on the client

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by leojkwan** [comment]
Re callback url, try adding one based on the specification from the doc into the accepted callbacks field on Auth0 admin. It should be easy. I can help you out this weekend if needed!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by leojkwan** [comment]
awesome work on this @sufeiiz! closing issue.
