### ISSUE TITLE
Audit initial application

### ISSUE THREAD

**Issue by leojkwan** [superfit-athletics/android#3]
I created the initial project based on some [RayWenderlich](https://www.raywenderlich.com/4738-your-first-kotlin-android-app/lessons/5) videos lol. I didn't do a whole lot besides download android studio, scaffold a new application and set the project identifier as 'com.superfit.android'.

Hopefully I didn't botch that up.

**Comment by sufeiiz** [comment]
Looks good! I think we should:
1. add more to .gitignore
2. delete the example tests
3. remove espresso dependency for now, again nothing to test yet!

**Comment by leojkwan** [comment]
What other types of data should be added to the .gitignore?
