### ISSUE TITLE
Networking Layer

### ISSUE THREAD

**Issue by sufeiiz** [superfit-athletics/android#6]
I believe the best way to approach our networking service is to use a repository pattern. The repository layer would decide when to fetch from Room database or the server, keeping that logic decoupled from views. Another discussion we should have is whether to pair Room with Rxjava or Kotlin Coroutines. I've used Room with Rxjava before, but will need to do a bit of research into how compatible it is with Coroutines.

**Comment by leojkwan** [comment]
I think that would be a great approach. I have some awareness of the repository pattern and leveraging this repos as a facade on top of our persistence and network layer make sense to me. Curious, would you use one main repo for all network calls, or would you separate repos based on the typo of resource it would pull from? I prefer the former, but I know some folks prefer to break networkClients/repos based on that criteria. For example, ProgramCatalogRepo, UserRepo etc.

Re: RxJava vs Kotlin Coroutines. I hear Rx is way more prevalent in the android dev community than it is in iOS land, let's go with that. Unless using RxJava incurs significant overhead or has been known for presenting unordinary development errors, I'd say use what you're comfortable with and has more developer mind share.

I will just watch, follow, and copy you.

**Comment by leojkwan** [comment]
also check out these swagger docs again. I made them public ~ https://app.swaggerhub.com/apis/superfit/superfit-api/1.0.0-oas3#/Program%20Catalogs/get_v2_programCatalogs__slug___version_

More to be added.

**Comment by sufeiiz** [comment]
I actually prefer breaking the repo down based on what kind of data it's holding. As the app grows, that main repo will get too big and messy, I would rather break it down. 

And for RxJava, yes it's been around for longer and more prevalent, but it's a really big library. Kotlin comes with collections, which makes some of Rxjavas operators irrelevant. Our main is asynchronous programming, which coroutines was built to do. If we ever cross the bridge where we need RxJava to handle more complex streams, we can discuss using both.

**Comment by leojkwan** [comment]
Re: RxJava— sounds good to me, I would enjoy learning how to use coroutines as well. Seems very similar to JS' async await syntax so not too far off.

Re: 1 big repo— Got you, I've seen both ways done, and although I actually prefer 1 big file of api network code, SuperFit iOS actually breaks them network clients based on resource.

I think separate repos can't hurt, are you thinking about having a "main repo" act as a facade to underlying "sub-repos"? So a main repo with an interface to call 'fetchProgram' 'fetchUser', but the respective implementations are in a "ProgramRepo" and "UserRepo"? 

Last Note: see #14. Long term move, but might offload a lot of tedious work writing networking layers based on swagger spec. That work would fall on me, (unless you have interest in writing some swagger json 😏).

**Comment by leojkwan** [comment]
Ultimate Decision Made-> Repo Pattern
